Update pipeline test and fix other bugs
ITMO-NSS-team/BIAM-Urb pull request #37
Opened 2024-09-04 14:15 UTC by KamilFatkhiev

- Обновил тест пайплайна по доступности
- Исправил обработку кварталов
- Исправил эндпоинт для получения контекста из таблиц

2024-09-04 14:22 UTC, Kiraprint commented on pipelines/tests/pipeline_test.py
> +total_access_questions = access_data_simple.shape[0]
перенести в root/tests/test_data

2024-09-04 14:24 UTC, Kiraprint commented on pipelines/tests/pipeline_test.py
> +total_access_questions = access_data_simple.shape[0]
остальную часть кода перенести в root/tests/pipelines/test_accessability_pipeline

2024-09-04 14:57 UTC, KamilFatkhiev commented on pipelines/tests/pipeline_test.py
> +total_access_questions = access_data_simple.shape[0]
напиши пожалуйста подробнее, что и куда ты предлагаешь перенести

это не те тесты, которые подразумевается запускать через pytest, если что

2024-09-06 08:17 UTC, Nunkyl submitted a review, later dismissed

2024-09-06 11:46 UTC, Kiraprint requested changes

2024-09-06 13:34 UTC, KamilFatkhiev commented on api/summary_tables_requests.py
>      if name_id and type:
Исправлено

2024-09-06 13:34 UTC, KamilFatkhiev commented on pipelines/tests/pipeline_test.py
> +    # ),  # more strictly evaluate consistency with the correct answer
Исправлено

2024-09-06 13:35 UTC, KamilFatkhiev commented on pipelines/tests/pipeline_test.py
> +total_access_questions = access_data_simple.shape[0]
Вчера обсудили этот момент. Тоже можно закрывать тред

2024-09-06 18:20 UTC, Kiraprint approved these changes

2024-09-09 08:04 UTC, Nunkyl approved these changes

2024-09-09 08:54 UTC, merged